title: TJ Maynes
email: tj@tjmaynes.com
description: >-
  Hacker / Entrepreneur | Remote 
baseurl: "/"
url: "https://tjmaynes.com"
twitter_username: tjmaynes
github_username:  tjmaynes

permalink: /post/:title:output_ext

plugins:
  - jekyll-feed

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - Gemfile
  - Gemfile.lock
  - vendor
  - README.md
  - .gitignore
  - Makefile
  - scripts/
